# Generated by Django 5.2.11 on 2026-07-14 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_file', models.ImageField(upload_to='certificate_templates/')),
                ('name_x', models.IntegerField(default=0)),
                ('name_y', models.IntegerField(default=800)),
                ('date_x', models.IntegerField(default=0)),
                ('date_y', models.IntegerField(default=950)),
                ('name_font_size', models.IntegerField(default=80)),
                ('date_font_size', models.IntegerField(default=45)),
                ('text_color', models.CharField(default='252,252,200', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandHoldingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='handholding/resumes/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='handholding/photos/')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('show_profile', models.BooleanField(default=False)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('preferred_counselling_mode', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10, null=True)),
                ('total_sessions', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_sessions', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandHoldingParticipantSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_no', models.PositiveIntegerField()),
                ('session_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_booked', 'Not Booked'), ('booked', 'Booked'), ('in_progress', 'In Progress'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HandHoldingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordering', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_name', models.CharField(blank=True, max_length=200, null=True)),
                ('advertiser_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('ad_platform', models.CharField(blank=True, max_length=100, null=True)),
                ('ad_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ad_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(blank=True, choices=[('handholding', 'Handholding')], max_length=50, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued')], default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='event.certificatetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, choices=[('seminar', 'Seminar'), ('webinar', 'Webinar')], max_length=20, null=True)),
                ('seminar_webinar_name', models.CharField(blank=True, max_length=255, null=True)),
                ('concerned_person_name', models.CharField(blank=True, max_length=150, null=True)),
                ('concerned_person_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('concerned_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('event_start_date', models.DateField(blank=True, null=True)),
                ('event_end_date', models.DateField(blank=True, null=True)),
                ('event_start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('event_end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('venue_type', models.CharField(blank=True, choices=[('college', 'College'), ('corporate', 'Corporate'), ('firm', 'Firm')], max_length=20, null=True)),
                ('event_mode', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI')], max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('session_status', models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
