# Generated by Django 5.2.11 on 2026-07-14 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        ('program_package', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_path1', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_path2', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('file_path_count', models.PositiveIntegerField(default=0)),
                ('file_path1_count', models.PositiveIntegerField(default=0)),
                ('file_path2_count', models.PositiveIntegerField(default=0)),
                ('report_status', models.CharField(blank=True, choices=[('not_received', 'Not Received'), ('received_locked', 'Received Locked'), ('received_unlocked', 'Received Unlocked'), ('v1_not_received', 'V1 Not Received'), ('v2_not_received', 'V2 Not Received'), ('v3_not_received', 'V3 Not Received'), ('v1_received', 'V1 Received'), ('v2_received', 'V2 Received'), ('v3_received', 'V3 Received')], max_length=50, null=True)),
                ('report_status_v2', models.CharField(blank=True, choices=[('not_received', 'Not Received'), ('received_locked', 'Received Locked'), ('received_unlocked', 'Received Unlocked'), ('v1_not_received', 'V1 Not Received'), ('v2_not_received', 'V2 Not Received'), ('v3_not_received', 'V3 Not Received'), ('v1_received', 'V1 Received'), ('v2_received', 'V2 Received'), ('v3_received', 'V3 Received')], default='v2_not_received', max_length=50, null=True)),
                ('report_status_v3', models.CharField(blank=True, choices=[('not_received', 'Not Received'), ('received_locked', 'Received Locked'), ('received_unlocked', 'Received Unlocked'), ('v1_not_received', 'V1 Not Received'), ('v2_not_received', 'V2 Not Received'), ('v3_not_received', 'V3 Not Received'), ('v1_received', 'V1 Received'), ('v2_received', 'V2 Received'), ('v3_received', 'V3 Received')], default='v3_not_received', max_length=50, null=True)),
                ('review_required', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program_package.package')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program_package.program')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_type', models.CharField(blank=True, choices=[('report', 'Report'), ('certificate', 'Certificate'), ('paid_doc', 'Paid Document')], max_length=20, null=True)),
                ('review_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('in_process', 'In Process'), ('pending_approval', 'Pending Approval'), ('submitted', 'Submitted')], default='not_submitted', max_length=20)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
