# Generated by Django 5.2.11 on 2026-04-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_booked', 'Not Booked'), ('booked', 'Booked'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('session_type', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingCounsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('lead', 'Lead'), ('assistant', 'Assistant')], max_length=50, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking_counsellors',
            },
        ),
        migrations.CreateModel(
            name='CounsellingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='counselling_notes/')),
                ('file2', models.FileField(blank=True, null=True, upload_to='counselling_notes/')),
                ('file3', models.FileField(blank=True, null=True, upload_to='counselling_notes/')),
                ('file4', models.FileField(blank=True, null=True, upload_to='counselling_notes/')),
                ('file5', models.FileField(blank=True, null=True, upload_to='counselling_notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.CharField(blank=True, max_length=150, null=True)),
                ('end_time', models.CharField(blank=True, max_length=150, null=True)),
                ('mode', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'slots',
            },
        ),
    ]
